name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: | 
        sudo mkdir /usr/local/share/ca-certificates/russian_trusted
        sudo cp certs/russian_trusted_root_ca_pem.crt /usr/local/share/ca-certificates/russian_trusted
        sudo cp certs/russian_trusted_sub_ca_pem.crt /usr/local/share/ca-certificates/russian_trusted
        sudo update-ca-certificates -v
        export GIGACHAT_AUTH_TOKEN=${{secrets.GIGACHAT_AUTH_TOKEN}}
        cargo test --verbose
