name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: | 
        mkdir /usr/share/pki/ca-trust-source/anchors
        cp certs/russian_trusted_root_ca_pem.crt /usr/share/pki/ca-trust-source/anchors
        cp certs/russian_trusted_sub_ca_pem.crt /usr/share/pki/ca-trust-source/anchors
        export GIGACHAT_AUTH_TOKEN=${{secrets.GIGACHAT_AUTH_TOKEN}}
        cargo test --verbose
